---
title: "05_combo.Rmd"
author: "Rayna M Harris"
date: March 13, 2017
output:
  md_document:
  variant: markdown_github
---
## Comparing Rayna's data and the Cembrowski data
  
```{r setup, echo=FALSE, message=FALSE, results='hide',comment=FALSE, warning=FALSE}
library(VennDiagram)

# set output file for figures 
knitr::opts_chunk$set(fig.path = '../figures/05_metaanalyses/')
```


```{r ImportFlattenData, echo=FALSE, message=FALSE, results='hide',comment=FALSE, warning=FALSE}
dissociation_venn123 <- read.table("../results/01_dissociation_venn123.txt")
dissociation_venn4 <- read.table("../results/01_dissociation_venn4.txt")
stress_venn123 <- read.table("../results/02_stress_venn123.txt")
stress_venn4 <- read.table("../results/02_stress_venn4.txt")
behavior_venn123 <- read.table("../results/03_behavior_venn123.txt")
behavior_venn4 <- read.table("../results/03_behavior_venn4.txt")
cembrowski_venn123 <- read.table("../results/04_cembrowski_venn123.txt")
cembrowski_venn4 <- read.table("../results/04_cembrowski_venn4.txt")


#flatten to lists not dfs
dissociation_venn123 <- unlist(apply(dissociation_venn123, 1, list), recursive = FALSE)
stress_venn123 <- unlist(apply(stress_venn123, 1, list), recursive = FALSE)
behavior_venn123 <- unlist(apply(behavior_venn123, 1, list), recursive = FALSE)
cembrowski_venn123 <- unlist(apply(cembrowski_venn123, 1, list), recursive = FALSE)
dissociation_venn4 <- unlist(apply(dissociation_venn4, 1, list), recursive = FALSE)
stress_venn4 <- unlist(apply(stress_venn4, 1, list), recursive = FALSE)
behavior_venn4 <- unlist(apply(behavior_venn4, 1, list), recursive = FALSE)
cembrowski_venn4 <- unlist(apply(cembrowski_venn4, 1, list), recursive = FALSE)
```


```{r CreateIntersections, echo=FALSE, message=FALSE, results='hide',comment=FALSE, warning=FALSE}
# extract the intersection all experiments
intersection <- Reduce(intersect, list(dissociation_venn123,stress_venn123,behavior_venn123, cembrowski_venn123))
intersection <- as.data.frame(intersection)
intersection <- t(intersection)
rownames(intersection) <- NULL
intersection <- as.data.frame(intersection)
colnames(intersection)[1] <- "gene"
intersection

write.csv(intersection, "./06_GO_MWU/05_metaanalyses_intersection.csv", row.names = F)

# extract the intersection between cembrowki and dissociation
cembrowskidissosication <- Reduce(intersect, list(cembrowski_venn4,dissociation_venn4))
cembrowskidissosication <- as.data.frame(cembrowskidissosication)
cembrowskidissosication <- t(cembrowskidissosication)
rownames(cembrowskidissosication) <- NULL
cembrowskidissosication <- as.data.frame(cembrowskidissosication)
colnames(cembrowskidissosication)[1] <- "gene"
cembrowskidissosication

write.csv(cembrowskidissosication, "./06_GO_MWU/05_metaanalyses_cembrowskidissosication.csv", row.names = F)

# extract the intersection cognition and dissociation
cognitiondissociation <- Reduce(intersect, list(behavior_venn4,dissociation_venn4))
cognitiondissociation <- as.data.frame(cognitiondissociation)
cognitiondissociation <- t(cognitiondissociation)
rownames(cognitiondissociation) <- NULL
cognitiondissociation <- as.data.frame(cognitiondissociation)
colnames(cognitiondissociation)[1] <- "gene"
cognitiondissociation

write.csv(cognitiondissociation, "./06_GO_MWU/05_metaanalyses_cognitiondissociation.csv", row.names = F)

# extract the intersection stress and dissociation
stressdissociation <- Reduce(intersect, list(stress_venn4,dissociation_venn4))
# list of 0

# extract the intersection cognition and dissociation
regionstressdissociation <- Reduce(intersect, list(stress_venn123,dissociation_venn123))
regionstressdissociation <- as.data.frame(regionstressdissociation)
regionstressdissociation <- t(regionstressdissociation)
rownames(regionstressdissociation) <- NULL
regionstressdissociation <- as.data.frame(regionstressdissociation)
colnames(regionstressdissociation)[1] <- "gene"
regionstressdissociation

write.csv(regionstressdissociation, "./06_GO_MWU/05_metaanalyses_regionstressdissociation.csv", row.names = F)

```

```{r VennDiagramRegion, echo=FALSE, message=FALSE, results='hide',comment=FALSE, warning=FALSE}
candidates <- list("Dissociation" = dissociation_venn123, "Cembrowski" = cembrowski_venn123, "Stress" = stress_venn123, "Cognition" = behavior_venn123)

prettyvenn <- venn.diagram(
  scaled=T,
  x = candidates, filename=NULL, 
  fill = c( "white", "white", "white", "white"),
  alpha = 0.5,
  #cex = 1, 
  fontfamily = "sans", #fontface = "bold",
  cat.default.pos = "text",
  #cat.dist = c(0.1, 0.1, 0.1), cat.pos = 1,
  cat.cex = 1, cat.fontfamily = "sans",
  col = "black"
  )
#dev.off()
grid.draw(prettyvenn)
```

```{r VennDiagramTreatement4, echo=FALSE, message=FALSE, results='hide',comment=FALSE, warning=FALSE}
candidates <- list("Dissociation" = dissociation_venn4,"Cembrowski" = cembrowski_venn4, "Stress" = stress_venn4, "Cognition" = behavior_venn4)

prettyvenn <- venn.diagram(
  scaled=T,
  x = candidates, filename=NULL, 
  fill = c( "white", "white", "white", "white"),
  alpha = 0.5,
  #cex = 1, 
  fontfamily = "sans", #fontface = "bold",
  cat.default.pos = "text",
  #cat.dist = c(0.1, 0.1, 0.1), cat.pos = 1,
  cat.cex = 1, cat.fontfamily = "sans",
  col = "black"
  )
#dev.off()
grid.draw(prettyvenn)
```

```{r VennDiagramTreatement3, echo=FALSE, message=FALSE, results='hide',comment=FALSE, warning=FALSE}
candidates <- list("Dissociation" = dissociation_venn4, "Cognition" = behavior_venn4)

prettyvenn <- venn.diagram(
  scaled=T,
  x = candidates, filename=NULL, 
  fill = c( "white", "white"),
  alpha = 0.5,
  #cex = 1, 
  fontfamily = "sans", #fontface = "bold",
  cat.default.pos = "text",
  #cat.dist = c(0.1, 0.1, 0.1), cat.pos = 1,
  cat.cex = 1, cat.fontfamily = "sans",
  col = "black"
  )
#dev.off()
grid.draw(prettyvenn)
```


```{r VennDiagramTreatementAnyCembrowski, echo=FALSE, message=FALSE, results='hide',comment=FALSE, warning=FALSE}
candidates <- list("Dissociation" = dissociation_venn4,"Cembrowski Region" = cembrowski_venn123, "Cognition" = behavior_venn4, "Dorsal vs venral" = cembrowski_venn4)

prettyvenn <- venn.diagram(
  scaled=T,
  x = candidates, filename=NULL, 
  fill = c( "white", "white", "white", "white"),
  alpha = 0.5,
  #cex = 1, 
  fontfamily = "sans", #fontface = "bold",
  cat.default.pos = "text",
  #cat.dist = c(0.1, 0.1, 0.1), cat.pos = 1,
  cat.cex = 1, cat.fontfamily = "sans",
  col = "black"
  )
#dev.off()
grid.draw(prettyvenn)
```

```{r VennDiagramTreatementNoCembrowski, echo=FALSE, message=FALSE, results='hide',comment=FALSE, warning=FALSE}
candidates <- list("Dissociation" = dissociation_venn4, "Stress" = stress_venn4, "Cognition" = behavior_venn4)

prettyvenn <- venn.diagram(
  scaled=T,
  x = candidates, filename=NULL, 
  fill = c( "white", "white", "white"),
  #alpha = 0.5,
  #cex = 1, 
  fontfamily = "sans", #fontface = "bold",
  cat.default.pos = "text",
  #cat.dist = c(0.1, 0.1, 0.1), cat.pos = 1,
  cat.cex = 1, cat.fontfamily = "sans",
  col = "black"
  )
#dev.off()
grid.draw(prettyvenn)
```

```{r VennDiagramRegionStressDissociation, echo=FALSE, message=FALSE, results='hide',comment=FALSE, warning=FALSE}
candidates <- list("Dissociation" = dissociation_venn123, "Stress" = stress_venn123)

prettyvenn <- venn.diagram(
  scaled=T,
  x = candidates, filename=NULL, 
  fill = c( "white", "white"),
  #alpha = 0.5,
  #cex = 1, 
  fontfamily = "sans", #fontface = "bold",
  cat.default.pos = "text",
  #cat.dist = c(0.1, 0.1, 0.1), cat.pos = 1,
  cat.cex = 1, cat.fontfamily = "sans",
  col = "black"
  )
#dev.off()
grid.draw(prettyvenn)
```