---
title: "heatmaps"
author: "Rayna M Harris"
date: "12/16/2017"
output: md_document
---

```{r setup, include=FALSE}
library(pheatmap)
library(viridis)
library(dplyr)

source("04_heatmapcolors.R")

# set output file for figures 
knitr::opts_chunk$set(fig.path = '../figures/04_heatmaps/')
```

Here is the function I wrote to make two heatmaps, one a png and one a pdf. The goal is to have the ~ top X number of genes that are differentially expressed according to treatment.


```{r}
dissocation_DEGes <- read.csv("../results/01_dissociation_DEGes.csv", header = T, check.names = F)
dissocation_df <-read.csv("../results/01_dissociation_colData.csv", header = T, row.names = 1)
dissocation_df <- dissocation_df %>% dplyr::select(Subfield, Treatment)
head(dissocation_DEGes)
```

```{r }
Heatmaps <- function(DEGes, ann_colors, df, main){
  
    myfile <-  paste("../figures/heatmaps/", substitute(DEGes), ".pdf", sep="")
  
  DEGes <- DEGes[order(DEGes$padjmin),]
  DEGes <- head(DEGes, 30)
  print(head(DEGes, 30))

 rownames(DEGes) <- DEGes$rownames
drop.cols <-colnames(DEGes[,grep("padj|pval|rownames", colnames(DEGes))])
DEGes <- DEGes %>% select(-one_of(drop.cols))
DEGes <- as.matrix(DEGes)
DEGes <- DEGes - rowMeans(DEGes)

  paletteLength <- 30
  myBreaks <- c(seq(min(DEGes), 0, length.out=ceiling(paletteLength/2) + 1), 
              seq(max(DEGes)/paletteLength, max(DEGes), length.out=floor(paletteLength/2)))
  
pheatmap(DEGes, show_colnames=F, show_rownames = T,
         annotation_col=df, annotation_colors = ann_colors, 
         annotation_row = NA, annotation_legend = FALSE,
         annotation_names_row = FALSE, annotation_names_col = FALSE,
         border_color = "grey60" ,
         color = viridis(30),
         clustering_method="average",
         breaks=myBreaks,
         clustering_distance_cols="correlation", 
         cluster_cols = F,
         main = main)  

pheatmap(DEGes, show_colnames=F, show_rownames = T,
         annotation_col=df, annotation_colors = ann_colors, 
         annotation_row = NA, annotation_legend = TRUE,
         annotation_names_row = FALSE, annotation_names_col = TRUE,
         treeheight_row = 0, treeheight_col = 10,
         fontsize = 7, 
         border_color = "grey60" ,
         color = viridis(30),
         width=3.5, height=3.25,
         clustering_method="average",
         breaks=myBreaks,
         clustering_distance_cols="correlation", 
         cluster_cols = F,
         main = main,
         filename =  myfile)
}
```


```{r heatmaps}
#colorpalette
dissocation_colors <- list(Treatment = c(control = (values=c("#ffffff")), 
                                         dissociated = (values=c("#525252"))),
                           Subfield = c(CA1 = (values=c("#7570b3")),
                                        CA3 = (values=c("#1b9e77")), 
                                        DG = (values=c("#d95f02"))))

# uses above "Heatmaps" function
# usage: name of matrix, color palette, lengend, title
Heatmaps(dissocation_DEGes, dissocation_colors, dissocation_df, "Cellular Dissociation")
```
