---
---
title: "04_Cembrowski.Rmd"
author: "Rayna M Harris"
date: December 16, 2017
output: md_document
---

## Reproducing the Cembrowski et al. study (Part II)

```{r setup, echo=FALSE, message=FALSE, results='hide',comment=FALSE, warning=FALSE}
#source("http://www.bioconductor.org/biocLite.R")
#biocLite("DESeq2")
library(DESeq2)
library(tidyverse)
library(plyr)
library(reshape2)

# user defined funcitons and options
source("resvalsfunction.R") 
```

First, I'll import the data from the previous script (Cembrowksi_analyze).

```{r import}
colData <- read.csv("../results/04_cembrowksi_colData.csv",header = T)
countData <- read.csv("../results/04_cembrowksi_countData.csv", header = T, row.names = 1)
```

```{r DifferentialGeneExpressionAnalysis, comment=FALSE, warning=FALSE, message=F}
dds <- DESeqDataSetFromMatrix(countData = countData,
                              colData = colData,
                              design = ~ Subfield + Treatment + Subfield * Treatment)
dds <- dds[ rowSums(counts(dds)) > 2, ] ## filter genes with 2+ counts
dds <- DESeq(dds) # Differential expression analysis
rld <- rlog(dds, blind=FALSE)
vsd <- vst(dds, blind=FALSE)
head(assay(vsd), 3)
head(assay(rld), 3)

write.csv(assay(vsd), "../results/04_cembrowksi_vsd.csv")
write.csv(assay(rld), "../results/04_cembrowksi_rld.csv")
```


```{r VennDiagram, echo=FALSE, message=FALSE, results='hide',comment=FALSE, warning=FALSE}
contrast1 <- resvals(contrastvector = c('Subfield', 'CA1', 'DG'), mypval = 0.1)
contrast2 <- resvals(contrastvector = c('Subfield', 'CA3', 'DG'), mypval = 0.1)
contrast3 <- resvals(contrastvector = c('Subfield', 'CA1', 'CA3'), mypval = 0.1)
contrast4 <- resvals(contrastvector = c('Treatment', 'ventral', 'dorsal'), mypval = 0.1)

#create a new DF with the gene counts
rldpvals <- assay(rld)
rldpvals <- cbind(rldpvals, contrast1, contrast2, contrast3, contrast4)
rldpvals <- as.data.frame(rldpvals)
rldpvals <- rldpvals[ , grepl( "padj|pval" , names( rldpvals ) ) ]

write.csv(rldpvals, "../results/04_cembrowksi_rldpvals.csv")
```

# Setup for GO analysis of CA1 aand 

```{r GOsetup, echo=FALSE, message=FALSE, comment=FALSE, warning=FALSE }
#create a new DF with the gene counts
GOpvals <- assay(rld)
GOpvals <- cbind(GOpvals, contrast1)
GOpvals <- as.data.frame(GOpvals)
GOpvals <- GOpvals[ , grepl( "padj|pval" , names( GOpvals ) ) ]
GOpvals$gene<-rownames(GOpvals)
GOpvals$logP <- log(GOpvals$pvalSubfieldCA1DG)
GOpvals <- GOpvals %>%
  select(gene, logP)

write.csv(GOpvals, "./06_GO_MWU/04_cembrowski_GOpvalsSubfieldCA1DG.csv", row.names = F)
```

```{r volcanos}
res <- results(dds, contrast =c("Treatment", "ventral", "dorsal"), independentFiltering = T, alpha = 0.05)
summary(res)

resOrdered <- res[order(res$padj),]
head(resOrdered, 5)

data <- data.frame(gene = row.names(res), pvalue = -log10(res$padj), lfc = res$log2FoldChange)
data <- na.omit(data)
data <- data %>%
  mutate(color = ifelse(data$lfc > 0 & data$pvalue > 1.3, 
                        yes = "ventral", 
                        no = ifelse(data$lfc < 0 & data$pvalue > 1.3, 
                                    yes = "dorsal", 
                                    no = "none")))
data$color <- as.factor(data$color)
summary(data)
write.csv(data, "../results/04_cembrowski_volcanoVentralDorsal.txt")


res <- results(dds, contrast =c("Subfield", "CA1", "DG"), independentFiltering = T, alpha = 0.05)
summary(res)

resOrdered <- res[order(res$padj),]
head(resOrdered, 5)

data <- data.frame(gene = row.names(res), pvalue = -log10(res$padj), lfc = res$log2FoldChange)
data <- na.omit(data)
data <- data %>%
  mutate(color = ifelse(data$lfc > 0 & data$pvalue > 1.3, 
                        yes = "CA1", 
                        no = ifelse(data$lfc < 0 & data$pvalue > 1.3, 
                                    yes = "DG", 
                                    no = "none")))
data$color <- as.factor(data$color)
summary(data)
write.csv(data, "../results/04_cembrowski_volcanoCA1DG.txt")
```


